import { eventSchema, type IntelligenceEvent } from "../domain/event";

export const demoEvents: IntelligenceEvent[] = eventSchema.array().parse([
  {
    id: "evt-orbit-3-release",
    eventType: "model_release",
    status: "published",
    titleZh: "示例｜Orbit AI 发布 Orbit 3，新增结构化工具调用",
    deckZh: "从文本生成升级为可约束的工具执行，产品流程需要重新评估。",
    whatChanged: "演示厂商 Orbit AI 在样例公告中发布 Orbit 3，并为 API 增加严格 JSON Schema 输出与并行工具调用能力。",
    before: "Orbit 2 只能逐个调用工具，复杂结构需要调用方二次校验。",
    after: "Orbit 3 支持并行工具调用，并可要求结果严格匹配给定 JSON Schema。",
    whyItMatters: "依赖多步骤 Agent 的团队可以减少格式修复和串行等待，但仍需重新跑现有工具参数与失败路径测试。",
    recommendedAction: "用 20 条现有工具调用用例对 Orbit 3 做一次兼容性回归，再决定是否切换。",
    affectedRoles: [
      { role: "product", level: "medium", impact: "可重新评估需要多工具协作的产品流程。" },
      { role: "developer", level: "high", impact: "需要验证 Schema、并行参数和失败重试是否兼容。" },
    ],
    evidenceLevel: "official",
    confidence: 0.96,
    needsReview: false,
    reviewReasons: [],
    announcedAt: "2026-08-25T09:30:00+08:00",
    effectiveAt: "2026-08-25T09:30:00+08:00",
    publishedAt: "2026-08-25T10:05:00+08:00",
    updatedAt: "2026-08-25T10:05:00+08:00",
    promptVersion: "G-01.v0.1+P-01.v0.1+P-02.v0.1",
    modelId: "mock-v1",
    sources: [
      { id: "src-orbit-announcement", publisher: "Orbit AI（演示）", title: "Introducing Orbit 3", url: "https://example.com/#orbit-3", sourceType: "official", publishedAt: "2026-08-25T09:30:00+08:00" },
      { id: "src-orbit-api-docs", publisher: "Orbit AI Docs（演示）", title: "Tool calling migration guide", url: "https://example.com/#orbit-tool-calling", sourceType: "official", publishedAt: "2026-08-25T09:35:00+08:00" },
    ],
    citations: [
      { id: "cit-orbit-schema", sourceId: "src-orbit-announcement", claim: "Orbit 3 增加严格 JSON Schema 输出。", supports: ["whatChanged", "after"] },
      { id: "cit-orbit-parallel", sourceId: "src-orbit-api-docs", claim: "Orbit 3 支持并行工具调用。", supports: ["whatChanged", "after"] },
    ],
  },
  {
    id: "evt-vector-api-sunset",
    eventType: "api_change",
    status: "published",
    titleZh: "示例｜Vector Cloud 将停用 v1 嵌入接口",
    deckZh: "旧路径将在 45 天后停止服务，调用方需要安排迁移。",
    whatChanged: "演示服务 Vector Cloud 宣布将在 2026 年 10 月 9 日停止 v1 嵌入接口，并提供新的批处理端点。",
    before: "客户端使用 /v1/embeddings 提交单批最多 64 条文本。",
    after: "客户端需迁移到 /v2/embeddings；旧端点在生效日后不再接受请求。",
    whyItMatters: "没有迁移的检索与知识库功能会在截止日后中断。",
    recommendedAction: "本周盘点所有 /v1/embeddings 调用，并在测试环境完成 v2 兼容验证。",
    affectedRoles: [
      { role: "developer", level: "high", impact: "需要修改调用路径并验证批量限制。" },
      { role: "product", level: "medium", impact: "需要把迁移工作加入近期版本计划。" },
    ],
    evidenceLevel: "official",
    confidence: 0.98,
    needsReview: false,
    reviewReasons: [],
    announcedAt: "2026-08-24T18:10:00+08:00",
    effectiveAt: "2026-10-09T00:00:00+08:00",
    publishedAt: "2026-08-24T18:45:00+08:00",
    updatedAt: "2026-08-24T18:45:00+08:00",
    promptVersion: "G-01.v0.1+P-01.v0.1+P-02.v0.1",
    modelId: "mock-v1",
    sources: [
      { id: "src-vector-changelog", publisher: "Vector Cloud（演示）", title: "v1 embeddings deprecation notice", url: "https://example.com/#vector-v1", sourceType: "official", publishedAt: "2026-08-24T18:10:00+08:00" },
    ],
    citations: [
      { id: "cit-vector-date", sourceId: "src-vector-changelog", claim: "v1 嵌入接口将在 2026 年 10 月 9 日停用。", supports: ["whatChanged", "effectiveAt", "after"] },
    ],
  },
  {
    id: "evt-atlas-pricing-review",
    eventType: "pricing",
    status: "needs_review",
    titleZh: "示例｜Atlas API 新缓存计费规则仍待人工核对",
    deckZh: "两个样例来源对生效范围的描述不一致，暂不自动发布结论。",
    whatChanged: "Atlas API 的样例价格页出现缓存输入新价格，但媒体摘要对适用模型范围的描述与价格页不同。",
    before: "缓存输入沿用标准输入价格。",
    after: null,
    whyItMatters: "高频长上下文任务的成本可能改变，但在范围核实前不应调整预算。",
    recommendedAction: "等待人工核对价格页适用模型和生效时间，再更新成本模型。",
    affectedRoles: [
      { role: "founder", level: "medium", impact: "月度推理预算可能变化。" },
      { role: "product", level: "medium", impact: "需要重新比较长上下文功能的单位经济性。" },
    ],
    evidenceLevel: "reported",
    confidence: 0.63,
    needsReview: true,
    reviewReasons: ["pricing_scope_conflict", "effective_date_missing"],
    announcedAt: "2026-08-23T14:00:00+08:00",
    effectiveAt: null,
    publishedAt: "2026-08-23T15:00:00+08:00",
    updatedAt: "2026-08-23T15:20:00+08:00",
    promptVersion: "G-01.v0.1+P-01.v0.1+P-02.v0.1",
    modelId: "mock-v1",
    sources: [
      { id: "src-atlas-pricing", publisher: "Atlas API（演示）", title: "Pricing", url: "https://example.com/#atlas-pricing", sourceType: "official", publishedAt: "2026-08-23T14:00:00+08:00" },
      { id: "src-atlas-report", publisher: "AI Market Wire（演示）", title: "Atlas introduces cache pricing", url: "https://example.com/#atlas-report", sourceType: "media", publishedAt: "2026-08-23T14:30:00+08:00" },
    ],
    citations: [
      { id: "cit-atlas-price", sourceId: "src-atlas-pricing", claim: "价格页出现缓存输入单独计费。", supports: ["whatChanged"] },
      { id: "cit-atlas-scope", sourceId: "src-atlas-report", claim: "媒体摘要给出了不同的适用模型范围。", supports: ["whatChanged", "reviewReasons"] },
    ],
  },
  {
    id: "evt-agent-eval-study",
    eventType: "research",
    status: "published",
    titleZh: "示例｜新评测研究指出 Agent 长任务失败集中在状态恢复",
    deckZh: "结论来自样例论文与复现实验，不等同于所有 Agent 产品都会失败。",
    whatChanged: "一项演示研究发布长任务 Agent 评测集，并报告状态恢复与工具参数错误是主要失败类别。",
    before: null,
    after: "公开了包含 120 个长任务案例的评测方法与错误分类。",
    whyItMatters: "团队可以把恢复能力和参数校验加入 Agent 上线门槛，而不仅关注最终答案分数。",
    recommendedAction: "从现有任务中选 10 条加入中断恢复和工具参数回归测试。",
    affectedRoles: [
      { role: "researcher", level: "medium", impact: "获得新的长任务评测分类参考。" },
      { role: "developer", level: "medium", impact: "需要补测任务恢复与参数校验。" },
    ],
    evidenceLevel: "corroborated",
    confidence: 0.88,
    needsReview: false,
    reviewReasons: [],
    announcedAt: "2026-08-22T11:00:00+08:00",
    effectiveAt: null,
    publishedAt: "2026-08-22T16:30:00+08:00",
    updatedAt: "2026-08-22T16:30:00+08:00",
    promptVersion: "G-01.v0.1+P-01.v0.1+P-02.v0.1",
    modelId: "mock-v1",
    sources: [
      { id: "src-agent-paper", publisher: "Agent Systems Lab（演示）", title: "RecoverBench: Evaluating long-horizon agents", url: "https://example.com/#recoverbench", sourceType: "research", publishedAt: "2026-08-22T11:00:00+08:00" },
      { id: "src-agent-replication", publisher: "Open Eval Group（演示）", title: "RecoverBench replication notes", url: "https://example.com/#recoverbench-replication", sourceType: "research", publishedAt: "2026-08-22T15:00:00+08:00" },
    ],
    citations: [
      { id: "cit-agent-cases", sourceId: "src-agent-paper", claim: "评测集包含 120 个长任务案例。", supports: ["whatChanged", "after"] },
      { id: "cit-agent-failures", sourceId: "src-agent-replication", claim: "复现实验观察到状态恢复和工具参数错误。", supports: ["whyItMatters"] },
    ],
  },
]);
