import { sourceDefinitionSchema, type SourceDefinition } from "./types";

const officialRssNote = "官方页面明确提供 RSS 入口；仅保存标题、链接、时间与不超过 4,000 字符的必要摘录。";
const officialAtomNote = "官方项目公开提供 Atom/Release 入口；仅保存发布标题、链接、时间与不超过 4,000 字符的必要摘录。";
const rssRobotsNote = "只访问公开 RSS 端点，不抓取登录页、付费墙或受访问控制页面。";

export const curatedSources: SourceDefinition[] = [
  {
    id: "src-openai-news",
    name: "OpenAI News",
    homepageUrl: "https://openai.com/news/",
    feedUrl: "https://openai.com/news/rss.xml",
    sourceType: "official",
    fetchMethod: "rss",
    status: "active",
    priority: 10,
    frequencyMinutes: 30,
    allowedHosts: ["openai.com"],
    authorizationStatus: "approved",
    termsNote: officialRssNote,
    robotsNote: rssRobotsNote,
  },
  {
    id: "src-google-blog",
    name: "Google Blog",
    homepageUrl: "https://blog.google/feed/",
    feedUrl: "https://blog.google/rss/",
    sourceType: "official",
    fetchMethod: "rss",
    status: "active",
    priority: 20,
    frequencyMinutes: 30,
    allowedHosts: ["blog.google"],
    authorizationStatus: "approved",
    termsNote: officialRssNote,
    robotsNote: rssRobotsNote,
  },
  {
    id: "src-deepmind-blog",
    name: "Google DeepMind",
    homepageUrl: "https://deepmind.google/blog/",
    feedUrl: "https://deepmind.google/blog/rss.xml",
    sourceType: "official",
    fetchMethod: "rss",
    status: "active",
    priority: 25,
    frequencyMinutes: 30,
    allowedHosts: ["deepmind.google"],
    authorizationStatus: "approved",
    termsNote: officialRssNote,
    robotsNote: rssRobotsNote,
  },
  {
    id: "src-github-changelog",
    name: "GitHub Changelog",
    homepageUrl: "https://github.blog/changelog/",
    feedUrl: "https://github.blog/changelog/feed/",
    sourceType: "official",
    fetchMethod: "rss",
    status: "active",
    priority: 30,
    frequencyMinutes: 30,
    allowedHosts: ["github.blog"],
    authorizationStatus: "approved",
    termsNote: officialRssNote,
    robotsNote: rssRobotsNote,
  },
  {
    id: "src-huggingface-blog",
    name: "Hugging Face Blog",
    homepageUrl: "https://huggingface.co/blog",
    feedUrl: "https://huggingface.co/blog/feed.xml",
    sourceType: "official",
    fetchMethod: "rss",
    status: "active",
    priority: 40,
    frequencyMinutes: 30,
    allowedHosts: ["huggingface.co"],
    authorizationStatus: "approved",
    termsNote: officialRssNote,
    robotsNote: rssRobotsNote,
  },
  {
    id: "src-aws-ai-blog",
    name: "AWS AI Blog",
    homepageUrl: "https://aws.amazon.com/blogs/machine-learning/",
    feedUrl: "https://aws.amazon.com/blogs/machine-learning/feed/",
    sourceType: "official",
    fetchMethod: "rss",
    status: "active",
    priority: 50,
    frequencyMinutes: 30,
    allowedHosts: ["aws.amazon.com"],
    authorizationStatus: "approved",
    termsNote: officialRssNote,
    robotsNote: rssRobotsNote,
  },
  {
    id: "src-nvidia-deep-learning",
    name: "NVIDIA Deep Learning",
    homepageUrl: "https://blogs.nvidia.com/blog/category/deep-learning/",
    feedUrl: "https://blogs.nvidia.com/blog/category/deep-learning/feed/",
    sourceType: "official",
    fetchMethod: "rss",
    status: "active",
    priority: 60,
    frequencyMinutes: 30,
    allowedHosts: ["blogs.nvidia.com"],
    authorizationStatus: "approved",
    termsNote: officialRssNote,
    robotsNote: rssRobotsNote,
  },
  {
    id: "src-cloudflare-ai",
    name: "Cloudflare AI",
    homepageUrl: "https://blog.cloudflare.com/tag/ai/",
    feedUrl: "https://blog.cloudflare.com/tag/ai/rss/",
    sourceType: "official",
    fetchMethod: "rss",
    status: "active",
    priority: 70,
    frequencyMinutes: 30,
    allowedHosts: ["blog.cloudflare.com"],
    authorizationStatus: "approved",
    termsNote: officialRssNote,
    robotsNote: rssRobotsNote,
  },
  {
    id: "src-ollama-releases",
    name: "Ollama Releases",
    homepageUrl: "https://github.com/ollama/ollama/releases",
    feedUrl: "https://github.com/ollama/ollama/releases.atom",
    sourceType: "official",
    fetchMethod: "atom",
    status: "active",
    priority: 80,
    frequencyMinutes: 30,
    allowedHosts: ["github.com"],
    authorizationStatus: "approved",
    termsNote: officialAtomNote,
    robotsNote: rssRobotsNote,
  },
  {
    id: "src-langchain-releases",
    name: "LangChain Releases",
    homepageUrl: "https://github.com/langchain-ai/langchain/releases",
    feedUrl: "https://github.com/langchain-ai/langchain/releases.atom",
    sourceType: "official",
    fetchMethod: "atom",
    status: "active",
    priority: 90,
    frequencyMinutes: 30,
    allowedHosts: ["github.com"],
    authorizationStatus: "approved",
    termsNote: officialAtomNote,
    robotsNote: rssRobotsNote,
  },
  {
    id: "src-vllm-releases",
    name: "vLLM Releases",
    homepageUrl: "https://github.com/vllm-project/vllm/releases",
    feedUrl: "https://github.com/vllm-project/vllm/releases.atom",
    sourceType: "official",
    fetchMethod: "atom",
    status: "active",
    priority: 100,
    frequencyMinutes: 30,
    allowedHosts: ["github.com"],
    authorizationStatus: "approved",
    termsNote: officialAtomNote,
    robotsNote: rssRobotsNote,
  },
  {
    id: "src-llamaindex-releases",
    name: "LlamaIndex Releases",
    homepageUrl: "https://github.com/run-llama/llama_index/releases",
    feedUrl: "https://github.com/run-llama/llama_index/releases.atom",
    sourceType: "official",
    fetchMethod: "atom",
    status: "active",
    priority: 110,
    frequencyMinutes: 30,
    allowedHosts: ["github.com"],
    authorizationStatus: "approved",
    termsNote: officialAtomNote,
    robotsNote: rssRobotsNote,
  },
].map((source) => sourceDefinitionSchema.parse(source));

export function getCuratedSource(sourceId: string): SourceDefinition | null {
  return curatedSources.find((source) => source.id === sourceId) ?? null;
}
